### ISSUE TITLE
Would love to see a list of the icons!

### ISSUE THREAD

**Issue by jackmcdade** [theutz/statamic-ant-design-icons#1]
Hey there, congrats on your first Statamic addon, great work!

I know _I_ would like to see the icons and know what all the options are, so I bet other people would too. Any way you can add that to the docs or README or something?

**Comment by theutz** [comment]
Thanks! Excellent point. I'll whip up a demo site sometime this week where I can list out all the icons, and then link it to the Addon and/or README.
